name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  tpa:
    description: "Request teleport to other player"
  tpaccept:
    description: "Accept other player teleport request"
  tpdeny:
    description: "Deny other player teleport request"